### ISSUE TITLE
problem downloading data with niak_test_all

### ISSUE THREAD

**Issue by angela-tam** [SIMEXP/niak#103]
I tried testing niak 0.13.4 with psom 1.2.0 on magma with niak_test_all.

I got the following error:
octave:1> addpath(genpath('/home/atam/niak-0.13.4'))
octave:2> addpath(genpath('/home/atam/psom-1.2.0'))
octave:3> psom_mkdir('test_niak')
ans =  1
octave:4> cd test_niak/
octave:5> niak_test_all 
--2015-11-20 15:02:50--  http://www.nitrc.org/frs/download.php/7241/data_test_niak_mnc1.zip
Resolving www.nitrc.org... 132.239.16.23
Connecting to www.nitrc.org|132.239.16.23|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2726269 (2.6M) [application/force-download]
Saving to: `/home/atam/test_niak/data_test_niak_mnc1/data_test_niak_mnc1.zip'

100%[=====================================================================================================================================>] 2,726,269   1.09M/s   in 2.4s    

2015-11-20 15:02:54 (1.09 MB/s) - `/home/atam/test_niak/data_test_niak_mnc1/data_test_niak_mnc1.zip' saved [2726269/2726269]

Deleting file '/home/atam/test_niak/data_test_niak_mnc1/data_test_niak_mnc1.zip' 
ans = 0
data =

  scalar structure containing the fields:

```
path = 
name = target_test_niak_mnc1-target_test_niak_mnc1-0.13.5.zip
url = 
type = target_test_niak_mnc1
```

--2015-11-20 15:02:58--  https://github.com/simexp/niak_target/archive/target_test_niak_mnc1-target_test_niak_mnc1-0.13.5.zip
Resolving github.com... 192.30.252.129
Connecting to github.com|192.30.252.129|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/SIMEXP/niak_target/zip/target_test_niak_mnc1-target_test_niak_mnc1-0.13.5 [following]
--2015-11-20 15:02:59--  https://codeload.github.com/SIMEXP/niak_target/zip/target_test_niak_mnc1-target_test_niak_mnc1-0.13.5
Resolving codeload.github.com... 192.30.252.145
Connecting to codeload.github.com|192.30.252.145|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: `/home/atam/test_niak/target_test_niak_mnc1-target_test_niak_mnc1-0.13.5/target_test_niak_mnc1-target_test_niak_mnc1-0.13.5'

```
[                                                                                     <=>                                              ] 84,562,211  4.91M/s   in 17s     
```

2015-11-20 15:03:19 (4.73 MB/s) - `/home/atam/test_niak/target_test_niak_mnc1-target_test_niak_mnc1-0.13.5/target_test_niak_mnc1-target_test_niak_mnc1-0.13.5' saved [84562211]

unzip:  cannot find or open /home/atam/test_niak/target_test_niak_mnc1-target_test_niak_mnc1-0.13.5/target_test_niak_mnc1-target_test_niak_mnc1-0.13.5.zip, /home/atam/test_niak/target_test_niak_mnc1-target_test_niak_mnc1-0.13.5/target_test_niak_mnc1-target_test_niak_mnc1-0.13.5.zip.zip or /home/atam/test_niak/target_test_niak_mnc1-target_test_niak_mnc1-0.13.5/target_test_niak_mnc1-target_test_niak_mnc1-0.13.5.zip.ZIP.
mv: cannot stat `/home/atam/test_niak/target_test_niak_mnc1-target_test_niak_mnc1-0.13.5/_/_': No such file or directory
ans =  1
ans = 0
warning: There was a problem unzipping the dataset: 
warning: I could not find the file or folder /home/atam/test_niak/target_test_niak_mnc1-target_test_niak_mnc1-0.13.5/target_test_niak_mnc1-target_test_niak_mnc1-0.13.5.zip
ans = 0
error: There was a problem downloading the target data
error: called from:
error:   /home/atam/niak-0.13.4/extensions/niak_test/niak_test_all.m at line 128, column 9
octave:5> 

I grabbed the test dataset using wget https://codeload.github.com/SIMEXP/niak_target/zip/target_test_niak_mnc1-target_test_niak_mnc1-0.13.5
and called niak_test_all  again and now it seems to be working.  Maybe there's an issue with niak_wget?  Or maybe we should have a message telling the user to manually download the test dataset when this happens.

**Comment by pbellec** [comment]
Not sure about this particular instance, I'd have to try and replicate, but I myself had troubles downloading from nitrc on a number of occasions. Sometimes the issue resolves by just trying multiple times (niak_test_all does not re-download components that were successfully downloaded). Sometimes it fails systematically, probably because of a closed port. Anyway, we are going to move all the target data etc to the recent github large file system. Github offers a great command line API that does not have an equivalent in NITRC, so we can automatize all release operations. We are already using it and will switch everything on this system in the next couple of months. As I have never experienced a problem pulling from github, this should solve this problem. I agree we should still mention the possibility of manually downloading datasets to users in case something goes astray.

**Comment by gdevenyi** [comment]
Having the same issue here:
```
>>> niak_test_all
--2016-06-16 15:13:06--  http://www.nitrc.org/frs/download.php/7241/data_test_niak_mnc1.zip
Resolving www.nitrc.org (www.nitrc.org)... 132.239.16.23
Connecting to www.nitrc.org (www.nitrc.org)|132.239.16.23|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2726269 (2.6M) [application/force-download]
Saving to: ‘/scratch/niak/data_test_niak_mnc1/data_test_niak_mnc1.zip’

100%[====================================================================================================================================================>] 2,726,269   --.-K/s   in 0.1s

2016-06-16 15:13:15 (17.8 MB/s) - ‘/scratch/niak/data_test_niak_mnc1/data_test_niak_mnc1.zip’ saved [2726269/2726269]

Deleting file '/scratch/niak/data_test_niak_mnc1/data_test_niak_mnc1.zip'
ans = 0
data =

  scalar structure containing the fields:

    path =
    name = target_test_niak_mnc1-0.13.6.zip
    url =
    type = target_test_niak_mnc1

--2016-06-16 15:13:15--  https://github.com/simexp/niak_target/archive/target_test_niak_mnc1-0.13.6.zip
Resolving github.com (github.com)... 192.30.252.123
Connecting to github.com (github.com)|192.30.252.123|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/SIMEXP/niak_target/zip/target_test_niak_mnc1-0.13.6 [following]
--2016-06-16 15:13:15--  https://codeload.github.com/SIMEXP/niak_target/zip/target_test_niak_mnc1-0.13.6
Resolving codeload.github.com (codeload.github.com)... 192.30.253.120
Connecting to codeload.github.com (codeload.github.com)|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 87849390 (84M) [application/zip]
Saving to: ‘/scratch/niak/target_test_niak_mnc1-0.13.6/target_test_niak_mnc1-0.13.6.zip’

100%[====================================================================================================================================================>] 87,849,390   511KB/s   in 2m 8s

2016-06-16 15:15:24 (671 KB/s) - ‘/scratch/niak/target_test_niak_mnc1-0.13.6/target_test_niak_mnc1-0.13.6.zip’ saved [87849390/87849390]

ans = 0
rm: cannot remove ‘/scratch/niak/target_test_niak_mnc1-0.13.6/niak_target-target_test_niak_mnc1-0.13.6’: Is a directory
ans =  1
warning: I could not find the file or folder /scratch/niak/target_test_niak_mnc1-0.13.6/target_test_niak_mnc1-0.13.6.zip
warning: called from
    psom_clean>sub_clean_file at line 110 column 5
    psom_clean at line 85 column 9
    niak_wget at line 106 column 5
    niak_test_all at line 125 column 29
ans = 0
--2016-06-16 15:15:25--  http://files.figshare.com/1861821/template_cambridge_basc_multiscale_mnc_sym.zip
Resolving files.figshare.com (files.figshare.com)... 52.16.198.89, 54.154.244.188
Connecting to files.figshare.com (files.figshare.com)|52.16.198.89|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://ndownloader.figshare.com/files/1861821 [following]
--2016-06-16 15:15:28--  https://ndownloader.figshare.com/files/1861821
Resolving ndownloader.figshare.com (ndownloader.figshare.com)... 52.16.30.47, 54.76.125.32
Connecting to ndownloader.figshare.com (ndownloader.figshare.com)|52.16.30.47|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://s3-eu-west-1.amazonaws.com/pfigshare-u-files/1861821/template_cambridge_basc_multiscale_mnc_sym.zip [following]
--2016-06-16 15:15:29--  https://s3-eu-west-1.amazonaws.com/pfigshare-u-files/1861821/template_cambridge_basc_multiscale_mnc_sym.zip
Resolving s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)... 54.231.133.4
Connecting to s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)|54.231.133.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 211786 (207K) [binary/octet-stream]
Saving to: ‘/scratch/niak/template_cambridge_basc_multiscale_mnc_sym/template_cambridge_basc_multiscale_mnc_sym.zip’

100%[====================================================================================================================================================>] 211,786     75.9KB/s   in 2.7s

2016-06-16 15:15:33 (75.9 KB/s) - ‘/scratch/niak/template_cambridge_basc_multiscale_mnc_sym/template_cambridge_basc_multiscale_mnc_sym.zip’ saved [211786/211786]

Deleting file '/scratch/niak/template_cambridge_basc_multiscale_mnc_sym/template_cambridge_basc_multiscale_mnc_sym.zip'
ans = 0
<CLIP>
```

This breaks the tests, so I can't tell if NIAK works.

**Comment by pbellec** [comment]
@angela-tam we moved all test data to github. In my experience this works smoothly. 

@gdevenyi somehow I missed this issue for a year.... I don't see a problem from your logs. If an error occurs it must be after that.
