### ISSUE TITLE
how to deal with new features, bug fixes and releases

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/niak#104]
Here is a proposition of procedure to deal with new features, bug fixes and releases for niak. When we're happy with a version, we'll post on the github wiki. 
 * if you need to change something in niak (add a feature, or fix a bug), create an issue.
 * Create a branch and try to fix the issue on the branch.
 * Commit on the branch. TRAVIS will automatically run some tests. The tests need to pass. Potentially you will have to ask for a new target to be generated to @poquirion . We need to figure out how to deal with branch specific targets. 
 * Do a pull request and request a code review by somebody else (e.g. @poquirion @cdansereau @surchs @yassinebha @amal or myself)
 * When everything is fine (changes are typcially requested as part of the review), merge into master. NB: we will use the master branch as our development branch.
 * If a change is an important bug fix, consider merging some of the changes into the main releases. At this stage, we only have boss active (it is on the niak-boss branch). But in the next couple of months we will have the COG release. Note that no new features or changes in pipeline design will be pushed to an existing release.
 * Optionally you can request (through a github issue) for a new release of niak-boss or niak-dev (the master branch) to be made (notify @poquirion ). This will appear as a link on the github page as well as a container on docker hub. Note that we should soon be using docker on guillimin and stark, so as soon as a release is available on docker hub it will automatically become available on production sites.

**Comment by surchs** [comment]
Sounds cool. Just a question re 

"_If a change is an important bug fix, consider merging some of the changes into the main releases. At this stage, we only have boss active (it is on the niak-boss branch)._"

Does this mean not having a new release for the bugifx (or some version number change)?

**Comment by pbellec** [comment]
Definitely have a new release for the bug fix (or in the near future). But it would not get a new name. We'd have a major release every two years or so, and then bug fixes released every once in a while (maybe every few months) for these releases. So overall there would not be many releases for users of a stable niak, and these releases would be bug fixes, without new features. The niak-dev would be where we would push all our new features etc, with more frequent releases.

**Comment by pbellec** [comment]
ok so it looks we have a plan. Will open separate issues to implement it.
