### ISSUE TITLE
fmri_preprocess files_in structure

### ISSUE THREAD

**Issue by illdopejake** [SIMEXP/niak#105]
Perhaps pipeline could crash and show an error if it finds > 3 underscores within the string for an individual fMRI image. This is because, I guess it uses the underscores to count fmri, then session, then run, but if there are underscores in the subject ID, it will throw everything off. Currently, fmri_preprocess works completely fine if there are underscores in the subject name, but anything assuming the structure is separated with underscores would crash.

**Comment by pbellec** [comment]
So I agree there should be some sanity checks on subject/session and run IDs. That's missing. 

Having said that we will change the way we grab results in the near future, and it will not be a problem anymore if there are _ in the subject ID.

**Comment by yassinebha** [comment]
I'll also integrate the function niak_purge_files_in in the preprocessing pipeline as a subfunction in the script, I'm calling it `prune_files_in`

**Comment by yassinebha** [comment]
I did the change on the branch iss105-106. You can test it @pbellec  and tell if it works, at the same time test the issu #106.

**Comment by pbellec** [comment]
I have commented on the pull request. I don't think it makes sense to have the code of prune_files inside the pipeline. Maybe make it a separate function called from the pipeline instead? And please double check the doc, there were lots of typo in there. Re the _, I am not sure _ in subject IDs is a problem, you'd have to dig into the grabber's code to make sure.

**Comment by pbellec** [comment]
I have merged the PR to master. Please create a separate issue to integrate the prune_files function as a separate utility. That's a small tool that's going to be very useful.
