### ISSUE TITLE
docker-niak gui support on mac osx

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/niak#108]
Currently docker-niak does only have command line support on mac osx, which sucks. Would it be possible to use this trick to add GUI support?
http://stackoverflow.com/questions/16296753/can-you-run-gui-apps-in-a-docker-container

**Comment by pbellec** [comment]
So the link I sent is not a viable option. Here a thread that was active recently and points at a solution, that could also work on windows:
https://github.com/docker/docker/issues/8710

Also looks like there is some work to integrate this feature directly in kitematic
https://github.com/docker/kitematic/pull/326

We need to explore if one of this route is feasible.

**Comment by poquirion** [comment]
We will now using jupyter as ui interface. Closing this issu.
