### ISSUE TITLE
Documentation of GLM Connectome seems awry

### ISSUE THREAD

**Issue by illdopejake** [SIMEXP/niak#110]
Was looking for some documentation on GLM Connectome the other day. The first place I went was here:
http://simexp.github.io/niak/pipe_glm_connectome.html  

Unfortunately, the content of the documentation at the above link seemed restricted to region growing and was not consistent with the input parameters or concepts behind GLM Connectome. I'm assuming this is a mistake?

**Comment by pbellec** [comment]
It's just a copy/paste of the region growing documentation that was supposed to be used as a starting point and was left undrafted. I indeed need to write that up.
