### ISSUE TITLE
fmri Preprocess grabber should allow custom template

### ISSUE THREAD

**Issue by yassinebha** [SIMEXP/niak#112]
Actually the fmri preprocess grabber (under scores files_types) only grab cambridge template. We should  have the option to specify a path for a custom template.

**Comment by pbellec** [comment]
Not sure what you mean. First, this template is only used to do dimension reduction in BASC, so I am not sure why you want to change it. Second, you can always change the content of the files structure generated by the grabber. It won't be simpler to have an option to point to a file.

**Comment by yassinebha** [comment]
here I'm talking about the template for scores prior. So, as you said, I created an option that point to a file.
