### ISSUE TITLE
Scores pipeline should spit in the output folder the prior partition and the template mask

### ISSUE THREAD

**Issue by yassinebha** [SIMEXP/niak#115]
In scores it is important to know what prior were used and the group mask. we should add them to the output folder.

**Comment by pbellec** [comment]
agreed

**Comment by yassinebha** [comment]
it is missing a `filesep` here https://github.com/SIMEXP/niak/blob/479369b1d304c83d83afc35971a3c5a3bbd3403a/extensions/surfstab/niak_pipeline_scores.m#L214
https://github.com/SIMEXP/niak/blob/479369b1d304c83d83afc35971a3c5a3bbd3403a/extensions/surfstab/niak_pipeline_scores.m#L222
so if you specify an output folder and forget to put the `/` at the end of the path it will generate the template and mask in the previous folder.

**Comment by pbellec** [comment]
@surchs in general when a brick takes a path as input (typically pipelines do), I call `niak_full_path` on this input:
`path_name = niak_full_path(path_name);`

This will append a `filesep` if necessary, but will also replace relative paths (like `documents` or `./documents`) by absolute paths (`/home/toto/documents/'). That's quite handy to be able to use relative path names when invoking pipelines.

**Comment by pbellec** [comment]
was looking to merge this, but there is a conflict. https://github.com/SIMEXP/niak/pull/120

Please let me know what you want to do with that.

**Comment by pbellec** [comment]
dropped support for the scores pipeline.
