### ISSUE TITLE
shortcut for quitting in the QC of fMRI preproc 

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/niak#128]
illdopejake wrote:
It would be cool if there was a keyboard shortcut to Quit. (Maybe there is and I just don't know about it?)

**Comment by yassinebha** [comment]
This issue is more OS specific, in ubuntu/windows  I close register with alt+F4. I don't know for OSX if there is an equivalent

**Comment by amanbadhwar** [comment]
Does command q not work? It works for me on OSX for register. I have not tried it with the QC pipeline though.
