### ISSUE TITLE
release 0.13.5

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/niak#131]
The fixes on the coregistration seem to be working fine. It does improve (slightly) registration in many cases, and improves dramatically on some. It is release time!

**Comment by pbellec** [comment]
Just realized this has still not been released. ??

**Comment by poquirion** [comment]
Nope, you told me to put in on the ice ( or it might have been miscomunication). Just give me a commit number (the hash) and i'll release it in niak-boss

**Comment by pbellec** [comment]
alright, current head should be good.

**Comment by poquirion** [comment]
That would be `a8f03799344f7ef6caf309464afa9bbb4698e7ca`

**Comment by pbellec** [comment]
cute name

**Comment by poquirion** [comment]
Done, we now need to update the "Fixes and feature part of the release": https://github.com/SIMEXP/niak/releases/tag/v0.13.5

Its a bit thin right now with only :

### Preprocessing pipeline:

  * New coregistration algorythm on the coregistration

**Comment by pbellec** [comment]
Done I have added a list of changes, based on the history of commits and attached logs. Thanks!!

**Comment by pbellec** [comment]
actually, we still need to push the release on docker hub.

**Comment by poquirion** [comment]
Ok

**Comment by poquirion** [comment]
Docker: done
