### ISSUE TITLE
Bunch of enhancement remarks from Aman and Christian for better QC workflow 

### ISSUE THREAD

**Issue by yassinebha** [SIMEXP/niak#139]
- Put the comment window before the fail/maybe/ok input
- Allow register to stay open while writing down the comment
- Add in the csv file for each subject the complete register command ready to be paste in a terminal.

**Comment by yassinebha** [comment]
* Integrate inter-run registration metric found in `quality_control/SUBJECT_ID/motion_correction/tab_coregister_motion.csv`

**Comment by pbellec** [comment]
we've now moved to html reports, which integrate all feedback received so far.
