### ISSUE TITLE
avoid calls to "docker stop niak" and "docker rm niak"

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/niak#145]
Depending on how the niak docker container is exited, the container somehow remains in either active or stopped state when a machine is restarted. With the current commands used to start niak with docker, the user is required to manually do something like 
```
docker stop niak
docker rm niak
```
It would be better to automate these operations by adding these two commands at the beginning of the niak alias.

**Comment by poquirion** [comment]
Added in the doc alias
