### ISSUE TITLE
add estimation of partial eta square in niak_glm

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/niak#148]

**Comment by pbellec** [comment]
So decided to go with Cohen's f2 instead. For the definition of the "local" variant of Cohen's f2 effect size (see Eq 2):
  Selya et al. A Practical Guide to Calculating Cohen’s f2, a Measure of Local 
  Effect Size, from PROC MIXED. Front Psychol. 2012; 3: 111.
  http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3328081/

**Comment by pyeror** [comment]
Cool!

ƒ2 effect sizes of 0.02, 0.15, and 0.35 are termed small, medium, and large, respectively.
Jacob Cohen (1988). Statistical Power Analysis for the Behavioral Sciences (second ed.). Lawrence Erlbaum Associates.

**Comment by poquirion** [comment]
C (contrast) is never set in  `bricks/fmri_preprocess/niak_brick_regress_confounds.m` so when it calls niak_glm.m, it crashes.

**Comment by pbellec** [comment]
F2 has been added to `niak_glm` and also as a map in the output of the GLM-connectome pipeline (with and without FDR threshold).
