### ISSUE TITLE
automatically archive the test reports from TRAVIS

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/niak#153]
The tests that run on TRAVIS generate a series of csv reports. Currently one of them is shown in the terminal, to help understand crashes without having to run the tests locally. As these CSV files are small (and could be compressed, it may make sense to automatically archive them using github. @poquirion do you think it would be possible with your simplegit tools?

**Comment by poquirion** [comment]
Yes, it is possible, but then I wonder how and where we would organise the data.

**Comment by pbellec** [comment]
we would create a github repo for it? Another option would be to use zenodo, maybe git is a bit of an overkill for this. Zenodo has a web API.

**Comment by poquirion** [comment]
Could simply print (cat *csv) them all at every test make sense too?

**Comment by pbellec** [comment]
well, currently one of them is printed. But the csv is so large it is impossible to make sense of the output from the travis console. It really has to be loaded on libreoffice or similar to be read properly.

**Comment by poquirion** [comment]
Migrating the testing to circle ci. The "result" directory is archive on the platform.
