### ISSUE TITLE
replace structural processing pipeline by minc-toolkit

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/niak#156]
currently niak as its own structural processing pipeline, forked from CIVET with a few added bits to it (notably a rudimentary brain extraction tool). This causes many problems, and is too large of a project to be maintained by SIMEXP. Needs to be replaced (urgently) by the minc-toolkit pipeline.

**Comment by pbellec** [comment]
@poquirion FYI here is a brick very similar to what needs to be developped. In this case, NIAK uses the CIVET pipeline for processing the T1, and simply renames the outputs. Can also be called on an existing CIVET output, in which case it simply copy/renames files. CIVET should be pretty similar to the minc-toolkit pipeline. 
https://github.com/SIMEXP/niak/blob/master/bricks/fmri_preprocess/niak_brick_civet.m

**Comment by poquirion** [comment]
It seems that the niak_demo_brick_xxx need some refractoring to be able to run smootly...

**Comment by pbellec** [comment]
yes. Maybe open a separate issue.

**Comment by poquirion** [comment]
Yé, I got something running.

**Comment by poquirion** [comment]
Seems that the minc templates have to be provided unziped to standard

**Comment by pbellec** [comment]
Interesting. Actually, if we switch to standard-pipeline, we won't need anymore most of the templates that ship with niak. This would reduce greatly the size of the package.

**Comment by poquirion** [comment]
Beast install itself in the `/opt/minc/share/beast-library-1.1` dir instead of `/opt/minc-itk4/share/beast-library-1.1`, I just copied the file there and it seem to work.

**Comment by pbellec** [comment]
maybe create an isuue on minc-toolkit

**Comment by poquirion** [comment]
I think the old `/opt/minc` setup/version is still the stable/supported system. 

We are using mni_icbm152_t1_tal_nlin_sym_09a but standard needs mni_icbm152_t1_tal_nlin_sym_09c, it need, for example, an eye mask. However, 09c has no  T2 relaxometrie.    http://nist.mni.mcgill.ca/?p=904

**Comment by pbellec** [comment]
not quite sure what the difference between 2009a and 2009c is. I likely went with the first one on the list... we do require a number of extra-mask of the fMRI preprocessing, but could get rid of some of the stuff. Also we will need to offer at least a symmetric and asymmetric option, but both probably ship in the MNI-templates package.

**Comment by poquirion** [comment]
I see that out template are all minc V1 should we stick with that or go with V2?

**Comment by pbellec** [comment]
minc V2. There was historically a bug for 4D files which prevented us to switch to minc2, but it has been long gone.

**Comment by pbellec** [comment]
So, after further experimenting, I found that the coregistration operations are not very numerically stable. This could be easily fixed, although at the cost of lots of computation, by averaging several coregistration rounds. We would need to parallelize these operations, as they will be heavy, which also means we need a proper psom pipeline. We'll therefore stick with what we have and expand it. We may want to plug mincbeast as a replacement to the region growing brain masking procedure.
