### ISSUE TITLE
bug in niak_grab_fmri_preprocess

### ISSUE THREAD

**Issue by amanbadhwar** [SIMEXP/niak#157]
opt_grab.filter.run is not selecting specified runs, but instead seems to be grabbing all runs.

**Comment by pbellec** [comment]
can you provide code/data to replicate the issue?

**Comment by amanbadhwar** [comment]
Let me know if this is not enough.

% grab preprocessed data
`opt_grab` = struct;
opt_grab.filter.run = {'rest645', 'rest1400', 'rest2500'};
opt_grab.exclude_subject = {'s0101463', 's0110809', 's0130716', 's0144495', 's0163059', 's0175151'};
opt_grab.type_files = 'scores';

path_preproc = '/gs/project/gsf-624-aa/abadhwar/NKI_fiftyplus_preprocessed2_with_niakissue100/fmri_preprocess_all_scrubb05';
data = niak_grab_fmri_preprocess(path_preproc, `opt_grab);`

**Comment by surchs** [comment]
I believe that [these are the offending lines in the function](https://github.com/SIMEXP/niak/blob/99b82f49a39460848f49b297907381c2fee39d87/commands/read_write/niak_grab_fmri_preprocess.m#L304). I will see if changing them fixes the behavior.

**Comment by surchs** [comment]
I was mistaken. The lines are fine. I believe we don't actually have a bug. The printout of the function is slightly confusing in the sense that the [session and run filters](https://github.com/SIMEXP/niak/blob/99b82f49a39460848f49b297907381c2fee39d87/commands/read_write/niak_grab_fmri_preprocess.m#L304) are applied after the [data quality control checks](https://github.com/SIMEXP/niak/blob/99b82f49a39460848f49b297907381c2fee39d87/commands/read_write/niak_grab_fmri_preprocess.m#L224). This means that although you may only be interested in one task of your dataset, you will get warnings for excessive motion or insufficient remaining time points for all available tasks. 

@amanbadhwar: I believe we never found anything in the grabbed datasets that we didn't expect to be there. So I am thinking the brick worked fine, it's simply the warnings that are a little confusing. 

I will open a second issue for that and fix it there. I suggest closing this issue.
