### ISSUE TITLE
Niak Read Vol fails on some but not all files, and not all the time

### ISSUE THREAD

**Issue by surchs** [SIMEXP/niak#16]
When I am running the scores pipeline on ABIDE, I have several files failing - after being reset a couple of times. I checked some error logs and they all said something like this

```
Something went bad ... the job has FAILED !                                                                                         
The last error message occured was :                                                                                                
niak:read: . There was a problem unzipping the file. Please check that the command 'gunzip -f' works, or change this command using the variable GB_NIAK_UNZIP in the file NIAK_GB_VARS

File /sb/home/surchs/code/niak/commands/read_write/niak_read_vol.m at line 236
File /sb/home/surchs/code/niak/extensions/surfstab/niak_brick_scores_fmri.m at line 161
File /sb/home/surchs/code/psom/psom_run_job.m at line 214               
File /sb/home/surchs/code/psom/psom_run_job.m at line 128
```

I then tried to open these the file with fsl and also tried loading it with niak_read_vol in octave - both worked. Not sure what is happening since about 1/3 of the files seems affected.

One example on peuplier would be `/media/database3/abide/abide_release_sym_gsc0_lp01/USM/fmri_0050528_session_1_run1.nii.gz`

**Comment by surchs** [comment]
I kinda still have that issue. With my current implementation of [the stability pipeline test script](https://github.com/SIMEXP/Projects/blob/master/Scores/Test/Scripts/test_stability_pipeline.m) I do get this error:

````
niak:read: . There was a problem unzipping the file. Please check that the command 'gunzip -f' works, or change this command using the variable GB_NIAK_UNZIP in the file NIAK_GB_VARS 
File /home/surchs/Code/niak/commands/read_write/niak_read_vol.m at line 236
File /home/surchs/Code/niak/extensions/surfstab/niak_brick_scores_fmri.m at line 184
File /home/surchs/Code/psom/psom_run_job.m at line 214
File /home/surchs/Code/psom/psom_run_job.m at line 128
```

This is when running things from inside the current docker/simexp image. Any suggestions?

**Comment by pbellec** [comment]
After checking the code, the volume is generated with a minc tool. The output is named .mnc.gz, but mincresample does not support automated zipping of outputs. So NIAK crashes when it is trying to unzip it. Use niak_brick_resample_vol instead of mincresample, this will solve the problem (it actually zips the output).
