### ISSUE TITLE
bug in niak_grab_qc_fmri_preprocess

### ISSUE THREAD

**Issue by porban** [SIMEXP/niak#160]
Data are not grabbed if in uncompressed mnc format. The reason is that it uses the extension of the template to define what anat/func files to look for, even though the compressed template is automatically copied during preprocessing.

**Comment by pbellec** [comment]
I would say that the right fix for this is to ensure that the template gets converted into the same type as the rest of the data.

**Comment by pbellec** [comment]
done.
