### ISSUE TITLE
include FD, rotations and translations series in the extra.mat file

### ISSUE THREAD

**Issue by cdansereau** [SIMEXP/niak#162]
using niak_build_frame_displacement we should export the Frame displacement along with the rotation and translation in XYZ in the _extra.mat file

**Comment by pbellec** [comment]
This is already implemented as part of issue #122. This PR is taking ages because of the many ramifications of changing the organization of preprocessed data, but it should get done in the coming weeks.

**Comment by pbellec** [comment]
BTW it is not saved in the extra.mat, which is restricted to covariates regressed from the data, but in a confounds.tsv file including every possible confound one may want to use.

**Comment by pbellec** [comment]
fMRI data are saved right after resampling. This together with the one-time generation and saving of all confounds allows users to preprocess data with alternative preprocessing choices very fast (only regression and smoothing have to be re-done).
