### ISSUE TITLE
Warning in BASC running matlab

### ISSUE THREAD

**Issue by cdansereau** [SIMEXP/niak#165]
running BASC on matlab the following function will be removed and need to be replaced:

Warning: The RandStream.setDefaultStream static method will be removed in a
future release.  Use RandStream.setGlobalStream instead.

> In RandStream.RandStream>RandStream.setDefaultStream at 456
>  In psom_set_rand_seed at 79
>  In psom_run_job at 65

**Comment by pbellec** [comment]
We've dropped matlab support.
