### ISSUE TITLE
BASC error in msteps: variable 'stab' not found

### ISSUE THREAD

**Issue by jonathandubois** [SIMEXP/niak#166]
Hi, 
I got the below error when running BASC with the following parameters. Preprocessing and region growing completed successfully. Please let me know what you think. 

Jon

opt.region_growing.thre_size = 800;
opt.grid_scales = [7:1:20]';
opt.scales_maps = [12 12 12];
opt.stability_tseries.nb_samps = 300;
opt.stability_group.nb_samps = 1000;

---

  Log file of job msteps_group (status failed) 

---

Warning: No display specified.  You will not be able to display graphics on the screen.
Warning: No window system found.  Java option 'MWT' ignored.

```
                        < M A T L A B (R) >
              Copyright 1984-2012 The MathWorks, Inc.
                R2012b (8.0.0.783) 64-bit (glnxa64)
                          August 22, 2012

----------------------------------------------------
Your MATLAB license will expire in 08 days.
Please contact your system administrator or
MathWorks to renew this license.
----------------------------------------------------
```

To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.

Warning: The RandStream.setDefaultStream static method will be removed in a
future release.  Use RandStream.setGlobalStream instead. 

> In RandStream.RandStream>RandStream.setDefaultStream at 456
>   In psom_set_rand_seed at 79
>   In psom_run_job at 65 

---

Log of the (matlab) job : msteps_group
Started on 23-Apr-2016 12:37:51
User: jonathan
host : cmfisher
system : unix

---

The job starts now !

---

Warning: The RandStream.setDefaultStream static method will be removed in a
future release.  Use RandStream.setGlobalStream instead. 

> In RandStream.RandStream>RandStream.setDefaultStream at 456
>   In psom_set_rand_seed at 79
>   In niak_brick_msteps at 153
>   In psom_run_job>sub_eval at 214
>   In psom_run_job at 128 
> Reading the stability contrast measure...
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci7.mat
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci8.mat
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci9.mat
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci10.mat
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci11.mat
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci12.mat
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci13.mat
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci14.mat
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci15.mat
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci16.mat
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci17.mat
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci18.mat
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci19.mat
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci20.mat
> Reading the stability matrices...
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci7.mat
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci8.mat
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci9.mat
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci10.mat
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci11.mat
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci12.mat
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci13.mat
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci14.mat
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci15.mat
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci16.mat
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci17.mat
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci18.mat
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci19.mat
>     /data/data03/jonathan/new_pvc/fmri/basc/stability_group/stability_group_sci20.mat
> Normalizing the stability matrices ...
> Forward scale selection : number of components (percentage of residual variance) - 1 (0.238) - 2 (0.120) - 3 (0.027) - Done
>     Best model found (score 0.026510) : 10 5 18 
> Random search of initial model ...
>     Percentage done :  0 - 5 - 10 - 15 - 20 - 25 - 30 - 35 - 40 - 45 - 50 - 55 - 60 - 65 - 70 - 75 - 80 - 85 - 90 - 95 - 100 - Done
>     Best model found (score 0.026403) : 5 18 9 
> Component-wise model optimization ...
>     Best model found (score 0.026403) : 5 9 18 
> Saving outputs in a mat file

---

Something went bad ... the job has FAILED !
The last error message occured was :
Error using save
Variable 'stab' not found.
File /home/jonathan/matlab/niak-boss-0.13.0/bricks/basc/niak_brick_msteps.m at line 243
File /home/jonathan/matlab/niak-boss-0.13.0/extensions/psom-1.0.2/psom_run_job.m at line 214
File /home/jonathan/matlab/niak-boss-0.13.0/extensions/psom-1.0.2/psom_run_job.m at line 128

---

Checking outputs

---

The output file or directory /data/data03/jonathan/new_pvc/fmri/basc/stability_group/msteps_group.mat has not been generated!
The output file or directory /data/data03/jonathan/new_pvc/fmri/basc/stability_group/msteps_group_table.csv has not been generated!

---

23-Apr-2016 12:37:58 : The job has FAILED
Total time used to process the job : 7.34 sec.

---

ans =

```
 1
```

---

OUTPUT QSUB

---

---

ERROR QSUB

---

No window system found.  Java option 'MWT' ignored.

**Comment by cdansereau** [comment]
The 'stab' variable is not created in the else condition of the niak_brick_msteps function
so the pipeline crash when the script try to save it at the end of the function.

**Comment by cdansereau** [comment]
@jonathandubois could you also post the FLAG's that you have specified in you script 
thank you

**Comment by jonathandubois** [comment]
Here are all of the flags and parameters that I used in the basc pipeline script: 

opt_g.min_nb_vol = 150;
opt_g.min_xcorr_func = 0.5;
opt_g.min_xcorr_anat = 0.5;
opt_g.type_files = 'rest';
files_in = niak_grab_fmri_preprocess('/data/data03/jonathan/fmri/preproc/',opt_g);
opt.folder_out = '/data/data03/jonathan/fmri/basc/';
opt.region_growing.thre_size = 800;
opt.grid_scales = [7:1:20]';
opt.scales_maps = [12 12 12];
opt.stability_tseries.nb_samps = 300;
opt.stability_group.nb_samps = 1000;
opt.flag_ind = true;
opt.flag_mixed = true;
opt.flag_group = true;
opt.flag_test = false;
pipeline = niak_pipeline_stability_rest(files_in,opt);

**Comment by jonathandubois** [comment]
I also tried basc with the grid_scales options provided in the niak_template_stability_rest.m file (below), but it produced the same error. 

opt.grid_scales = [10:10:100 120:20:200 240:40:500]'; 
opt.scales_maps = repmat(opt.grid_scales,[1 3]);

**Comment by pbellec** [comment]
@jonathandubois my guess at this stage is that it is a general matlab bug. For the past couple of years I have not done much testing on matlab and it is very possible it fails. Do you have access to octave on your system? If yes please try to run your script that way and let me know if it works. In any case I will try to reproduce and fix the error, but it is just to avoid you being stuck.

**Comment by pbellec** [comment]
we completely dropped support for matlab. NIAK is supposed to run from a container, including octave.
