### ISSUE TITLE
option to pass header to niak_read_minc 

### ISSUE THREAD

**Issue by colmhenry** [SIMEXP/niak#169]
In cases where a user wants to read in many files with the same dimensions and does not otherwise need the minc headers, it would be useful to be able to pass a header as an optional argument to niak_read_minc so that the header parsing (which is time consuming) only needs to happen once.

**Comment by pbellec** [comment]
I am working on two new functions `niak_read_data_nifti` and `niak_read_data_minc` which only load the data array, for an existing header structure.

**Comment by pbellec** [comment]
The pull request is ready, but this somehow breaks our test. I need to investigate why.
