### ISSUE TITLE
niak_write_vol does not check header before saving

### ISSUE THREAD

**Issue by surchs** [SIMEXP/niak#17]
[niak_write_vol](https://github.com/SIMEXP/niak/blob/scores/commands/read_write/niak_write_vol.m) does apparently not check whether the dimensions in the header under `hdr.details.dim` match the actual data dimensions. As a result, you can save 3D data with a 4D header without any warnings or prompts.

Loading the same data with niak_read_vol() however throws an error because the data dimensions don't match the header.

**Comment by pbellec** [comment]
Hi Sebastian,

So this is the expected behaviour: the size of vol and hdr.info overrides anything in hdr.details. But it should write a valid header though, so that is definitely a problem. Does this happen in minc or nifti?

**Comment by surchs** [comment]
This happened in nifti for me. I think the scenario was: pulling a 4D nifti header and then trying to save a 3D array. I have made a hack-workaround in [niak_brick_scores_fmri](https://github.com/SIMEXP/niak/blob/master/extensions/surfstab/niak_brick_scores_fmri.m#L170). With minc, there don't seem to be any problems.

**Comment by pbellec** [comment]
I see. The nii reader/writer are going to get a full revamp soon, so I'll check on this again once the revamp is complete . Also, I think your branch scores was quite updated, and I have a feeling this is fixed in master.
