### ISSUE TITLE
niak_model_select should return the selected model as well

### ISSUE THREAD

**Issue by surchs** [SIMEXP/niak#179]
Currently `niak_model_select` only returns the subject IDs and row IDs of the selected model, not the model matrix itself. This means that the user has to perform an additional step to mask the original, unfiltered model with the returned row IDs and then select the columns according to his specifications.

Since Matlab allows to unpack return arguments into fewer variables, adding an additional return argument shouldn't lead to any problems with old code.

**Comment by pbellec** [comment]
Makes sense. Go ahead and implement it if you have the chance.
