### ISSUE TITLE
niak_normalize_model could update the contrasts to include specified interactions

### ISSUE THREAD

**Issue by surchs** [SIMEXP/niak#184]
Currently it is possible that the user requests an interaction term to be added to a model by [niak_normalize_model](https://github.com/SIMEXP/niak/blob/master/commands/fmristat/niak_normalize_model.m) but the returned model does not include that interaction and the user does not receive a warning about this.

This can happen in 2 ways:
1. If the user requests an interaction between two variables that are not part of the supplied model. For example, a model contains the covariates `Age`, `Sex` and `IQ` but the user requests an interaction between `Weight` and `Income`. This is addressed in #182.
2. If the user requests a possible interaction to be added but does not add a contrast for that interaction. In the above example, the user requests an interaction between `Age` and `Sex` with the name `age_sex` to be added to the model. But since he failed to add a contrast with the name `age_sex` to `OPT.CONTRAST`, the interaction will be [created](https://github.com/SIMEXP/niak/blob/master/commands/fmristat/niak_normalize_model.m#L262) and then [deleted](https://github.com/SIMEXP/niak/blob/master/commands/fmristat/niak_normalize_model.m#L300) again without a warning.

By contrast, the user can request that an intercept be added to the model with `OPT.FLAG_INTERCEPT` and even if no contrast is specified for the intercept, a contrast of `0` will be added for the user and the intercept will stay in the model.

I think this type of behaviour makes sense for the interaction as well. After all, if the user requests an interaction to be added they should expect the function to add it to the model. Since this functionality shouldn't break backwards compatibility, I'd add that.

@pbellec what do you think?

**Comment by pbellec** [comment]
1. I don't think users will access/read warnings. 
2. You could in theory add an interaction term to regress it as confounds, and then leave it out of the model. This is convoluted, but not impossible. 
3. Users will be able to review their model in the upcoming GLM dashboard, which be much more effective than a warning to convey what happened. So I will focus on developing the dashboard instead of adding warnings in the logs.
