### ISSUE TITLE
niak_read_hdr_minc fails because of 'missing field time'

### ISSUE THREAD

**Issue by surchs** [SIMEXP/niak#193]
Currently preprocessing a test subset of Simons VIP data. On slice time correction, I got the following traceback:

```
Something went bad ... the job has FAILED !
The last error message occured was :
structure has no member 'time'
File /software/CentOS-6/applications/octave/3.8.1/share/octave/3.8.1/m/miscellaneous/getfield.m at line 41
File /sb/home/surchs/quarantine/niak-v0.13.5/commands/read_write/niak_read_hdr_minc.m at line 285
File /sb/home/surchs/quarantine/niak-v0.13.5/commands/read_write/niak_read_minc.m at line 66
File /sb/home/surchs/quarantine/niak-v0.13.5/commands/read_write/niak_read_vol.m at line 255
File /sb/home/surchs/quarantine/niak-v0.13.5/bricks/fmri_preprocess/niak_brick_slice_timing.m at line 308
File /sb/home/surchs/quarantine/niak-v0.13.5/extensions/psom-v1.2.0/psom_run_job.m at line 252
File /sb/home/surchs/quarantine/niak-v0.13.5/extensions/psom-v1.2.0/psom_run_job.m at line 166
```

The original resting file can be found at `/gs/project/gsf-624-aa/simons_vip/TRIAL/14703.x3/rest_2.mnc'

Not sure what the error message is pointing to. Any ideas?

**Comment by pbellec** [comment]
So after inspecting the file, it is missing the description of the "time" variable. In particular it has unknown TR. This has to be fixed by proper conversion from DICOM or NIFTI, or can be manually added with `minc_modify_header`. I am not closing this issue though, because the error message from `niak_read_vol` should be improved.

**Comment by surchs** [comment]
Yes, that's what we found as well. Repeating the conversion in a way that doesn't destroy the time info in the header also fixes the loading problem. But I agree on the error message
