### ISSUE TITLE
niak_wget fails on Matlab

### ISSUE THREAD

**Issue by surchs** [SIMEXP/niak#195]
Found this while running `niak_test_all` on Matlab:

```
Warning: There was a problem downloading the test data: wget:
/usr/local/MATLAB/R2016a/sys/os/glnxa64/libstdc++.so.6: version
`CXXABI_1.3.8' not found (required by
/usr/lib/x86_64-linux-gnu/libicuuc.so.55)

> In niak_wget (line 94)
  In niak_test_all (line 114) 
Warning: There was a problem unzipping the dataset: unzip:  cannot find or
open /home/surchs/data_test_niak_mnc1/data_test_niak_mnc1.zip,
/home/surchs/data_test_niak_mnc1/data_test_niak_mnc1.zip.zip or
/home/surchs/data_test_niak_mnc1/data_test_niak_mnc1.zip.ZIP.

> In niak_wget (line 104)
  In niak_test_all (line 114) 
Warning: I could not find the file or folder
/home/surchs/data_test_niak_mnc1/data_test_niak_mnc1.zip 
> In psom_clean>sub_clean_file (line 115)
  In psom_clean (line 90)
  In niak_wget (line 106)
  In niak_test_all (line 114) 

ans =

     0

Error using niak_test_all (line 117)
There was a problem downloading the test data
```

I am assuming there is a problem with gzip.

**Comment by pbellec** [comment]
Ouch, I am scared of this error message. Matlab has a very dirty approach to packaging, bundling and over-riding system's libraries using its own. This may break many tools invoked by the command line. A notable example is the minc tools when compiled with dynamic libraries, as matlab forces its own version of the hdf5. This is a guess at this stage. 

Coud you run `printenv` in a terminal (outside Matlab) and again through a system call inside maltab, and run a diff on the outputs?

**Comment by poquirion** [comment]
We could control the env variable at execution for external tools.

**Comment by pbellec** [comment]
matlab re-initializes its environement variables at every system call. Ho yeah.

**Comment by pbellec** [comment]
by the way this thread is relevant (it describes the problem with HDF5 libraries). For the record, in that particular instance I was unable to solve the problem. Looks like `ldd path_to_wget` is the correct instruction to trace the problem, not `printenv`. Just replace `path_to_wget` by the full path to `wget` (can be retrieved in a terminal using `which wget`), and run the command both in a terminal and from matlab through a system call. 

There is also this thread from mathworks (http://www.mathworks.com/matlabcentral/answers/18064-system-wget). I haven't read it through, but the lack of answer over the past 5 years is not reassuring...

**Comment by surchs** [comment]
So [here are my environment variables](https://gist.github.com/surchs/3dbc269b553f47c4ef9dc4166f79542d)

**Comment by surchs** [comment]
`-bash: syntax error near unexpected token `'env -i bash -ilc "wget"''`

outside of Matlab

**Comment by poquirion** [comment]
you have two ' at the end

**Comment by poquirion** [comment]
Sorry, I should be more precise, `system('env -i bash -ilc "wget"')` should replace the plain `system('wget')` call in niak_wget.

**Comment by surchs** [comment]
```
surchs@ace-ws-4:~$ system('env -i bash -ilc "wget"') > outside_wget_env.txt
-bash: syntax error near unexpected token `'env -i bash -ilc "wget"''
```

not sure where they come from

**Comment by surchs** [comment]
oho, I see

**Comment by poquirion** [comment]
So, line 92 of niak_wget.m

``` diff
--- [status,msg] = system(['wget ' data.url ' -P ' data.path]);
+++ [status,msg] = system(['env -i bash -ilc "wget ' data.url ' -P ' data.path ' "']);
```

**Comment by surchs** [comment]
Ok, so this lets me execute `wget`. Great stuff. However it seems to download the file, delete the file and then the folder where the file was. I'll see how it fares on octave

**Comment by pbellec** [comment]
alright, googled more. Maybe try to replace the system call by `urlread`, a native Octave/Matlab command, which I only just discovered by googling :)

**Comment by pbellec** [comment]
OK need to experiment with `urlread` but it actually looks like it is to read text files, not binary archives.

**Comment by surchs** [comment]
So @poquirion code works. I messed up my path and dumped the data into `/home/surchs/home/surchs/...` so I thought it didn't generate. Seems to work fine now.

**Comment by pbellec** [comment]
I think this is an acceptable solution. As we don't call `wget` anywhere else in niak (that is the whole point of having `niak_wget`, we just have to change that one system call.

**Comment by surchs** [comment]
The only issue seems to be that you don't get the dynamic shell output in the Matlab shell. 

This is what you get:

```
niak_wget(data)
Deleting file '/home/surchs/tmp/niak_test/bonga/data_test_niak_mnc1.zip' 

ans =

     0


ans =

     0
```

**Comment by surchs** [comment]
I'm cluttering github in my free time...

**Comment by pbellec** [comment]
So the solution seems to not be robust across shells. In any case NIAK does not support matlab anymore. It's supposed to run from a container with octave. I am closing the issue, won't fix.
