### ISSUE TITLE
Columns of part variable in stability_group_sci*.mat

### ISSUE THREAD

**Issue by jonathandubois** [SIMEXP/niak#197]
I'm not sure if this is the right place to be posting this question, but I'm having trouble understanding the output of the BASC stability group analysis. Specifically, within the basc_output/stability_group directory, I would like to know what the columns (7 in my case) of the stability_group_sci*.mat part variable represent.

From the help file of the niak_threshold_hierarchy.m I see that if 
"multiple number of classes are specified, then PART is an array and PART(:,s) is the partition associated with OPT.THRESH(s)" How can I determine what thresholds were used and what thresholds each column represents?

**Comment by pbellec** [comment]
Hi @jonathandubois ,

The NITRC forum may be a better place:
http://www.nitrc.org/forum/forum.php?forum_id=1821
But I like the github issue system as well. 

Anyhow, for better or for worst, in the BASC algorithm I left three parameters be relatively uncoupled: the number of clusters in individual analyses (K), the number of clusters in the group analysis (L) and the final number of group consensus clusters (M). For a given K, we explore various values of L, in a neighbourhood of K, and select (K,L,M) to maximize the stability contrast (defined as the silhouette of the group stability matrix, using the M group consensus clusters - note that the matrix itself only depends on K and L). So the integer `nb_classes_ind` is the number of individual clusters for that particular analysis.  The vector `nb_classes` is a list of L in a neighbourhood of K. The vector `nb_classes_final` is the list of M values that maximize the contrast for each pair (K,L). So you have one value K, several values L and one value M for each L. Each column of PART is the optimal partition corresponding to a triplet (K,L,M). Specifically, `part(:,ii)` corresponds to `nb_classes_ind` individual clusters (it's a single value), `nb_classes(ii)` group clusters, and `nb_classes_final(ii)` group consensus clusters. 

Typically, we do not explore the content of these files. Instead, we use the parameters generated in `msteps_group_stable.csv` and re-run the pipeline a second time, specifying these parameters into `opt.scales_maps`. This generates nifti volumes of the consensus partitions, and associated stability maps, for a specific triplet (K,L,M). We then pick the group consensus clusters and use that in whatever follow-up analysis we are planning.   

I hope this helps. Best,

Pierre
