### ISSUE TITLE
external subtypes can break niak_brick_subtype_weight visualization of sorted weight matrix

### ISSUE THREAD

**Issue by surchs** [SIMEXP/niak#227]
This one is pretty clear but not so clear to fix. [niak_brick_subtype_weight](https://github.com/SIMEXP/niak/blob/subtype/extensions/subtype/niak_brick_subtype_weight.m#L204) tries to save the sorted weight matrix as a figure. For sorting, it relies on the linkage from the subtype brick that gives an order to the subjects. 

When we use an external subtype, this step is skipped (i.e. no subtype is created on the current data, since we use an external subtype). The brick then [takes the external subtype file](https://github.com/SIMEXP/niak/blob/subtype/extensions/subtype/niak_brick_subtype_weight.m#L198) and grabs the [subject order from that](https://github.com/SIMEXP/niak/blob/subtype/extensions/subtype/niak_brick_subtype_weight.m#L199). Now this is obviously nonsense as soon as we use external subtypes because the subjects that go into making the subtypes (sample A) and the subjects for which we compute the weights (sample B) are not the same. So attempting to sort one group on the order of the other is wrong.

Unfortunately this error is only raised in the case where sample A > sample B because the subject order of sample A is a vector the max(subj_order_a) = length(sample_a). So if sample B > sample A, instead of sorting the weight matrix of B we are slicing it. If sample A > sample B, we get an error because now we have positional information elements that don't exist in sample B (e.g. put subject 100 at position 3 when sample B only has 80 subjects).

I think there are 3 options to fix this:
1. save an unsorted weight matrix in the case of an external subtype
2. compute the linkage and subject order even when using an external subtype and then sort the weights by that
3. assign the subjects to the (external) cluster with the biggest weights and then sort them randomly inside the cluster. Use this sorting for the weight matrix

I think option 2 makes the most sense, option 3 is computationally cheaper and option 1 is the easiest (aside from not saving a sorted weight matrix figure). Any opinions?

**Comment by pbellec** [comment]
I really think option 3 makes the most sense. Option 2 is bad: if you specify subtypes, you want the visualization to reflect those subtypes, not different modes estimated independently. You can definitely extract weights, and then a "winner take all" subject partition out of it. Then you can extract an order using `niak_part2order`. The algorithm is pretty basic and described in the help. It's not great but I used it quite a bit during the BASC-FIR project.

**Comment by angela-tam** [comment]
I'm going to vote for option 3.

**Comment by angela-tam** [comment]
Should we put in a flag for external subtypes for the brick then?  I think I've worked out how to implement option 3.
