### ISSUE TITLE
niak_qc_fmri_preproc has hardcoded .mnc.gz paths, fails on anything else

### ISSUE THREAD

**Issue by surchs** [SIMEXP/niak#251]
[niak_qc_fmri_preproc](https://github.com/SIMEXP/niak/blob/master/commands/visualization/niak_qc_fmri_preproc.m#L108) calls the [qc grabber](https://github.com/SIMEXP/niak/blob/master/commands/read_write/niak_grab_qc_preprocess.m) without any options. While the grabber seems to support different file formats, this makes it default to '.mnc.gz' and then fail when the preprocessed data is in any other format (e.g. unzipped mnc or nifit).

**Comment by yassinebha** [comment]
this way of QCing is no longer maintained use this instead https://github.com/SIMEXP/qc_fmri_preprocess

**Comment by pbellec** [comment]
@yassinebha please remove any deprecated code

**Comment by yassinebha** [comment]
ok, what if i put it in a simexp/niak_qc_register repos I feel bad to just kill it

**Comment by surchs** [comment]
I actually think it's not a bad idea to keep it for now. The reason I wanted to use the script is that for exhaustive QC the web-based workflow is not ideal for me yet. I'd prefer to go through the subjects one by one with the possibility to move through the volumes

**Comment by poquirion** [comment]
@yassinebha, you don't rely kill it: its git, you can always go back to when it existed.
