### ISSUE TITLE
nu_correct is broken on guillimin

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/niak#254]

**Comment by poquirion** [comment]
@pbellec, can you give more details? I am reading the slack thread and all I see is that: "so nu_correct is broken on guillimin good thing we don't need it just created an issue".

**Comment by poquirion** [comment]
here is what I get when I run nu_correct on guillimin on a test file:

```
nu_correct in.mnc.gz out.mnc
Processing:.................................................Done
[...]
Processing:.................................................Done
Number of iterations: 46 
CV of field change: 0.000955504
```
The file out.mnc seems to be properly corrected too.
