### ISSUE TITLE
Please install widgetsnbextension or ipywidgets 4.0

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/niak#255]
I would like to include our html/javascript pipeline reports inside ipython notebook. But there are some missing libraries in the current niak_jupyter docker image.

**Comment by yassinebha** [comment]
this sounds like if we put more effort on integrating octave on beaker notebook it would payoff.
https://github.com/twosigma/beaker-notebook/issues/4305
https://github.com/twosigma/beaker-notebook/issues/3208

**Comment by poquirion** [comment]
Hello, ipywidgets Version: 5.2.2 is already installed, should I force regression to 4.0?

**Comment by poquirion** [comment]
@pbellec can you show what error you get?
