### ISSUE TITLE
niak_visu_surf camlight

### ISSUE THREAD

**Issue by angela-tam** [SIMEXP/niak#257]
When using Octave to call niak_visu_surf, even within the niak docker container, I get the following error:

> > niak_visu_surf(mask,ssurf)
> > warning: the 'camlight' function is not yet implemented in Octave
> > 
> > Please read `http://www.octave.org/missing.html' to learn how you can
> > contribute missing functionality.
> > 
> > error: 'camlight' undefined near line 237 column 6
> > error: called from:
> > error:   /home/angela/git/niak/commands/visualization/niak_visu_surf.m at line 237, column 6

It also looks like there are other MATLAB only functions in the code, like lighting (line 239) and material (line 240).

**Comment by pbellec** [comment]
we are not supporting matlab anymore. I doubt the 3D viewer will ever work well in Octave. Only chance to get a decent viewer will be through javascript tools. I need to make a big clean up and get rid of this kind of deprecated code. In the meantime we need to start using another tool (icesurf, connectome workbench, ?) to generate our surface images.
