### ISSUE TITLE
links not found

### ISSUE THREAD

**Issue by claramoreau9** [SIMEXP/niak#259]
links not found 
https://raw.githubusercontent.com/SIMEXP/niak/master/template/niak_template_stability_fir.m
https://github.com/SIMEXP/niak/blob/master/template/niak_template_basc_fir.m

**Comment by pbellec** [comment]
So that's in the tutorial http://niak.simexp-lab.org/niak_tutorial_basc_fir.html

Needs to be updated and replaced by a notebook, like the fMRI preprocessing tutorial.
