### ISSUE TITLE
scores pipeline constrains data to priors, bad for rmaps

### ISSUE THREAD

**Issue by surchs** [SIMEXP/niak#260]
As people keep using the scores pipeline to generate simple seed maps we started to run into an issue due to the peculiarities of the scores pipeline. Specifically, for scores, we [constrain the brain mask to the priors that are used with the pipeline](https://github.com/SIMEXP/niak/blob/master/extensions/surfstab/niak_brick_scores_fmri.m#L216). I am still determining if this is even necessary (I believe not). But one consequence is that if you run scores with only two small priors (in order to get two seed maps), your seed maps end up being constrained to these two priors as well.

Proposed short term fix:
- [ ] keep the original mask for seed map computation and use the constrained mask for scores

Long term:
- [ ] Figure out if constraining the mask is necessary for the scores algorithm and if not, get rid of it entirely.

**Comment by pbellec** [comment]
not completely clear, but it probably makes sense to compute subtype weights restricted to a grey matter mask. But maybe the maps could be specified to the subtypes pipeline. r-maps and dual regression can be generated without a mask. Having said that, it would make sense for scores itself to use a full brain parcellation and grey matter mask.

**Comment by pbellec** [comment]
rmaps are now generated using the connectome pipeline.
