### ISSUE TITLE
Modify and add some stats to subtype analysis: niak/extensions/subtype/niak_brick_chi_cramer.m

### ISSUE THREAD

**Issue by phildi** [SIMEXP/niak#261]
I'm not sure if I'm creating this "issue" properly ... but alas. Let me know if it should be done differently.

For the stats in this section, I would consider adding a "William's correction", since the values are often low. Likewise, I would suggest adding a post-hoc analysis of each of the subtypes in relation to the groups, that includes a "Yates correction". Finally, a Fishers Exact test for independence should be more accurate in the post-hoc analysis and would provide odds ratios and a confidence interval. Determining the Chi-Stat would still be necessary to calculate the Cramer's V, though ... and the Yates correction will make the "V" more conservative and likely more reliable. 

I'm no stats master, so feel free to correct me; but that is my impression when looking at the code, etc.

ps and a Bonferroni correction should be included in the post-hoc analysis ...

**Comment by pbellec** [comment]
If we want to explore more advanced tests I think we should do that in R separately from the pipeline. Our main analysis are based on GLM and continuous weights.
