### ISSUE TITLE
Empty rmaps using Scores pipeline

### ISSUE THREAD

**Issue by amanbadhwar** [SIMEXP/niak#267]
Using a template with a high number of parcels (such as 77) gives empty rmap_part. Works with lower number of parcels.

**Comment by pbellec** [comment]
So the maps are not empty, but the Fisher's transform leads to "Inf" values. We need to think how to handle this without completely distorting the subtype similarity scores.

**Comment by pbellec** [comment]
Thought more about this. We should probably simply not Fisher-transform our r-maps.

**Comment by pbellec** [comment]
The connectome pipeline generates r-maps without Fisher corrections. So if the subtype pipeline starts from these outputs, there will be no "Inf" problem.
