### ISSUE TITLE
add graphviz to the niak docker

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/niak#28]
With graphviz missing, it's not possible to show dependency graphs using PSOM.

**Comment by pbellec** [comment]
@poquirion please close this issue when you manage to build the upgraded docker image.

**Comment by poquirion** [comment]
Well I have problem with evince still. It seems that we have libraries that are 32 bit but we need them to be 64 bit...


```
root@86822489b7b3:/etc# evince
evince: error while loading shared libraries: libSM.so.6: cannot open shared object file: Permission denied
```

**Comment by poquirion** [comment]
see issue  #71
