### ISSUE TITLE
Links giving 'not found' error

### ISSUE THREAD

**Issue by amanbadhwar** [SIMEXP/niak#284]
For the subtyping pipeline wiki at https://github.com/SIMEXP/niak/wiki/Subtyping-pipeline, provided links give a page not found error when clicked.

**Comment by pbellec** [comment]
Fixed. But this documentation needs fixing. In the meantime, it is better to work from https://github.com/SIMEXP/niak_tutorials/blob/master/niak_tutorial_subtype_cobre.ipynb
