### ISSUE TITLE
QC report pipeline some typo and bugs 

### ISSUE THREAD

**Issue by yassinebha** [SIMEXP/niak#298]
- In [L167]( https://github.com/SIMEXP/niak/blob/master/reports/fmri_preprocess/niak_report_fmri_preprocess.m#L167) `jin = in.group.summary_func;` should be replaced by `jin = in.group.summary_anat`;
- A random code paste from [L273](https://github.com/SIMEXP/niak/blob/master/reports/fmri_preprocess/niak_report_fmri_preprocess.m#L273) to L275

**Comment by pbellec** [comment]
Alright, so I have applied the fixes in the issue289 branch. I'll create a PR. Please review and check I have implemented the changes correctly once the tests have completed.

**Comment by yassinebha** [comment]
All good
