### ISSUE TITLE
niak_Matlab test on magma

### ISSUE THREAD

**Issue by yassinebha** [SIMEXP/niak#3]
niak test on Matlab in magma.
Created niak branch called "niak_matlab" , fixed a minor compatibility bug and pushed the branch to github. je piepline stopped after  31 fail.

path result on magma: /scratch/pbellec/yassinebha/results
path target on magma: /scratch/pbellec/yassinebha/target_niak-boss-0.12.14/﻿

the log message  for the fiirst failed job fp_sica_subject1_run1 :

---

Spatial independent component analysis

---

Reading data /scratch/pbellec/yassinebha/results/demoniak_preproc/intermediate/subject1/regress_confounds//fmri_subject1_session1_motor_cor.mnc.gz ...
Reading brain mask /scratch/pbellec/yassinebha/results/demoniak_preproc/anat/subject1/func_subject1_mask_stereonl.mnc.gz ...
Correction of the mean of time series ...
Performing spatial independent component analysis with 60 components, this might take a while ...

---

Something went bad ... the job has FAILED !
The last error message occured was :
**Error using inv**
Too many output arguments.
File /scratch/pbellec/yassinebha/niak/commands/sica/niak_sica.m at line 943
File /scratch/pbellec/yassinebha/niak/commands/sica/niak_sica.m at line 183
File /scratch/pbellec/yassinebha/niak/bricks/sica/niak_brick_sica.m at line 238
File /scratch/pbellec/yassinebha/psom/psom_run_job.m at line 214
File /scratch/pbellec/yassinebha/psom/psom_run_job.m at line 128

**Comment by pbellec** [comment]
We don't support matlab anymore.
