### ISSUE TITLE
add docker to install instructions

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/niak#30]
The current installation page only give the full recipe for local install. The default should be for people to use docker, as it ensures reproducible results.
https://registry.hub.docker.com/u/simexp/niak/

**Comment by pbellec** [comment]
Done http://niak.simexp-lab.org/niak_installation.html . But it needs to be further improved and tested.

**Comment by poquirion** [comment]
I am working on a full docker simex/niak installation and running protocol on the website_update_28mai branch

**Comment by poquirion** [comment]
merge website_update_28mai  with gh-pages. Still need to add the procedure for debian with the (XAUTH setup)[http://stackoverflow.com/a/25280523/2367407]

**Comment by poquirion** [comment]
Tried to get gui working with the new mac procedure for docker with no effect around April 1st.

**Comment by poquirion** [comment]
refer to issue #70

**Comment by poquirion** [comment]
refer to issue #108
