### ISSUE TITLE
Add f2 results to output in niak_brick_glm_connectome.m

### ISSUE THREAD

**Issue by poquirion** [SIMEXP/niak#303]
The file is in `niak/extensions/glm_connectome/`

The value is computed but not given to the user. @pbellec Can you confirm that f2 just need to be added in the `save(files_out.results,[...],'f2')` call. I will do a 0.18.1 release.

**Comment by pbellec** [comment]
I think you would need to add under line 471 
`f2 = results.f2;`

and then you can save it yes.

**Comment by poquirion** [comment]
in 0.18.1
