### ISSUE TITLE
fdr correction in niak_brick_association_test.m is independent for each subtype

### ISSUE THREAD

**Issue by surchs** [SIMEXP/niak#325]
FDR correction for contrasts in [niak_brick_association_test](https://github.com/SIMEXP/niak/blob/master/extensions/subtype/niak_brick_association_test.m#L296) should be applied across all subtypes and networks at once. Currently we give the p_values in a network x subtype array. `niak_fdr` operates on the columns of this array, resulting in independent fdr corrections for each subtype across networks. The correct behaviour would be to first flattening the array of p_values into a vector to ensure a correct correction.

This affects both current master and the #263 branch currently in #313

**Comment by pbellec** [comment]
you should make a separate branch and merge into master asap. I'll merge back in #263

**Comment by surchs** [comment]
@pbellec: what do you think?

**Comment by pbellec** [comment]
merged into issue263. Trying to merge into master now.

**Comment by pbellec** [comment]
Merged to master.
