### ISSUE TITLE
derive global variables from PSOM to NIAK

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/niak#33]
global variables in niak_gb_vars should use the values defined in PSOM, when psom is present.

**Comment by poquirion** [comment]
I fixed it for "gb_niak_tmp", but is there any other variable where it is usefull/needed?

**Comment by pbellec** [comment]
gb_niak_language
 gb_niak_language_version
 gb_niak_OS 
 gb_niak_user

I think they have an equivalent in PSOM (gb_niak_xxxx would be gb_psom_xxx)

**Comment by poquirion** [comment]
Got them all
_version 
_language 
_tmp
_OS
_gb_vars_local
_user': 2
_language_version 
_path_demo

**Comment by pbellec** [comment]
Not sure that _gb_vars_local and _path_demo should be merged (the demo data
for psom and niak are different).

Pierre Bellec
http://simexp-lab.org/brainwiki/doku.php?id=pierrebellec
Telephone              (1) 514 713 5596
SIMEXP lab            http://simexp-lab.org

**Comment by surchs** [comment]
Interesting. So Octave apparently handles this ```endif```` statement. However, Matlab does not. So these commits to (master)[https://github.com/SIMEXP/niak] currently break niak on Matlab. 

Unless I don't understand the syntax, it seems that this is just a quirky way of ending an if-statement in Octave. I would suggest we get rid of it as some people (me) use Matlab. @poquirion: I can do this if you want.
