### ISSUE TITLE
simplify niak releases

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/niak#35]
Releasing a new version of NIAK currently includes:
  * Generate a target for tests using niak_test_all with `opt.flag_target = true`. 
  * Zip the output folder `target` under the name `target_test_niak_mnc1-xxxx.zip`, where xxxx is the new version number (e.g. 0.13.0).
  * Release the target on [http://www.nitrc.org/frs/?group_id=411](NITRC) in the `test_niak` package. 
  * Change the variable `gb_niak_version` in the file [niak_gb_vars](https://github.com/SIMEXP/niak/blob/master/commands/misc/niak_gb_vars.m)  (line 88).
  * Create a new tag on the local git repo `git tag -a vxxxx`
  * Push the new tag `git push --tags`
  * Edit the release page at https://github.com/SIMEXP/niak/releases/edit/vxxxx and describe the main changes with the previous release.
  * Create a new [build script](https://github.com/SIMEXP/Projects/tree/master/docker) for docker.
  * build and push a new docker image, called simexp/niak:xxxx . Also push the same image under the `tag simexp/niak:xxxx simexp/niak:latest`
  * push the niak images to docker (`docker push niak:xxxx` `docker push niak:latest`)
  * start bash from the docker image, zip the /home/niak folder under the name `niak-boss-xxxx.zip`. 
  * release the zip on [nitrc](http://www.nitrc.org/frs/?group_id=411) as part of the niak package. 

In addition, to deploy on a server:
  * wget the niak zip archive from nitrc
  * copy psom_gb_vars_local.m from a previous release
  * copy commands/misc/niak_gb_vars.m from a previous release.

This is *awfully* complicated but, fortunately, can be simplified a lot.

**Comment by pbellec** [comment]
Leads to simplify:
  * includes somehow the dependency of niak on the brain connectivity toolbox and psom as part of the git release. Not sure whether that is possible but worth investigating. This would avoid pushing the niak release to nitrc altogether. 
  * Link the niak repo on docker with the niak repo on github. This will automatically build and release the xxxx and latest images. 
  * Which, btw, would be more efficient if the templates of niak where split into a separate repo, that would get updated less often. That way new niak images would typically change only by a very thin layer of pure .m code. 
  * Implement a version for targets separate from the niak version. The targets will be generated independently from niak, and much much more infrequently. 

If all of that works, creating a new niak release would basically just include changing the niak version in niak_gb_vars.m, creating a new tag and pushing to github. The docker images would be created automatically. And if we use docker to run niak on servers, all we would need to do is invoke the latest niak image.

**Comment by pbellec** [comment]
Alright, so another fun fact. When making a new release of the target for the tests, it is necessary to change a new variable `gb_niak_target_test`. It contains the version of the target (formatted like YYYY-MM-DD). BUT once the target is released on NITRC, it is assigned a random URL. This URL has to be manually added line 68 in `niak_wget`. We need to move to a different place to release the targets, otherwise we will have to add this manual step for every new release of target data for tests.

**Comment by pbellec** [comment]
I have created a new repo for niak testing
https://github.com/SIMEXP/niak_test

I have also applied to early access to github large file support. I have installed the associated software and it's super easy to use. We'll use that repo to release new test data, which will appear on a predictable  URL.

**Comment by poquirion** [comment]
Started testing automatic release on https://github.com/poquirion/docker_build.

**Comment by poquirion** [comment]
Since it is not that big, I will put the the target in niak_test. I will use tags make package and pull these package to run tests.

**Comment by pbellec** [comment]
Great! As soon as simexp get approved for lfs we will simply transfer them over.

**Comment by poquirion** [comment]
The release tool has now its own [git repo](https://github.com/SIMEXP/release_tools).  

To do the release, we still need to:
Add a valid `psom_gb_vars_local.m` where the package is installed.
Manually trigger the a (not so) automatic docker image build [here](https://hub.docker.com/r/simexp/niak-boss/~/settings/automated-builds/).

**Comment by poquirion** [comment]
Release issue should be posted on the [release_tools](https://github.com/SIMEXP/release_tools) site.
