### ISSUE TITLE
Jobs crash after midnight singularity machine time

### ISSUE THREAD

**Issue by yassinebha** [SIMEXP/niak#356]
jobs/pipelines on singularity (guillimin) , that last more that 24h, crash after right on new internal date change insingularity.

the only way to make them wok is to shut down singularity session then open a new one

**Comment by poquirion** [comment]
Its seems to be the monitor that somehow gets disconnected. Just do 

```
tail -r results/logs/PIPE_history.txt
``` 
and you will see where the pipeline is at.
