### ISSUE TITLE
niak_gb_vars global variable error

### ISSUE THREAD

**Issue by angela-tam** [SIMEXP/niak#371]
Not sure this is relevant because I thought we were going to stop supporting matlab, but since it's mentioned in the function after all....

Line 40 does not work in matlab and generates the following error:
` global GB_NIAK = struct()
                ↑
Error: The expression to the left of the equals sign is not a valid target for an
assignment.`

A fix that seems to work would be
`global GB_NIAK`
`GB_NIAK = struct();`

**Comment by pbellec** [comment]
no Matlab support.
