### ISSUE TITLE
spm crashes in recent containers

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/niak#373]
@angela-tam has started to integrate spm tools in psom/niak, in her spm_container project.

With the boss containers spm12 compiles and runs smoothly.

Unfortunately with the cog containers we get an error, e.g.

```
[in2,out2,opt2] = spm_brick_realign (in, out, opt);
error: octave_base_value::write(): wrong type argument 'int16 scalar'
```

**Comment by pbellec** [comment]
Note from https://en.wikibooks.org/wiki/SPM/Octave
For compilation of the SPM MEX files for Octave, run the following:
```
cd /home/login/spm12/src
make distclean PLATFORM=octave
make PLATFORM=octave && make install PLATFORM=octave
```

**Comment by poquirion** [comment]
I had problems with linkage of the dependencies in the containers. I had to explicitly export the libraries in the LD_PATH before compilation:
I will need to check the spm compilation details...
