### ISSUE TITLE
build fail with commit a86e33f2b309bd21c659edac21b1e8b32f7fcbd7

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/niak#38]
After inspecting the travis logs, the difference starts in the regression of confounds, and the difference with the target are tiny. After checking the faulty commit it turns out that the formula for regression in niak_glm was modified for a more numerically stable method which likely explains the change. We should simply ignore this difference and release a new target.

**Comment by poquirion** [comment]
Right on Pierre, I've apply the following patch and got exacte outputs!
We just need to publish a new release with the (x'*x)\x'*y; notation


----------------------
diff --git a/commands/statistics/niak_glm.m b/commands/statistics/niak_glm.m
index a1b067a..4165ec9 100644
--- a/commands/statistics/niak_glm.m
+++ b/commands/statistics/niak_glm.m
@@ -146,8 +146,8 @@ K = size(x,2);
 if size(x,1)~=N
     error('X should have the same number of rows as Y');
 end
- 
-beta = (x'*x)\x'*y;              % Regression coefficient 
+
+beta = (x'*x)^(-1)*x'*y;         % Regression coefficients
 e = y-x*beta;                    % Residuals
 
 if isfield(opt,'test')
@@ -159,7 +159,7 @@ if isfield(opt,'test')
             if ~isfield(model,'c')
                 error('Please specify MODEL.C for performing a t-test')
             end
-            c = model.c(:);
+            c = model.c;
             std_e = sqrt(sum(e.^2,1)/(N-K));        % Standard deviation of the noise
 
             d     = sqrt(c'*(x'*x)^(-1)*c);         % Intermediate result for the t-test
@@ -182,7 +182,7 @@ if isfield(opt,'test')
             if ~isfield(model,'c')
                 error('Please specify MODEL.C for performing a F test')
             end
-            c = model.c(:);
+            c = model.c;
             s  = sum(e.^2,1);  % Estimate of the residual sum-of-square of the full model
             x0 = x(:,~model.c);
             p0 = size(x0,2);
diff --git a/commands/statistics/niak_lse.m b/commands/statistics/niak_lse.m
index b2b55a5..e39dff2 100644
--- a/commands/statistics/niak_lse.m
+++ b/commands/statistics/niak_lse.m
@@ -94,7 +94,7 @@ c = c(:);
 if size(x,1)~=N
     error('X should have the same number of rows as Y');
 end
-beta = (x'*x)\x'*y; % Regression coefficients
+beta = (x'*x)^(-1)*x'*y; % Regression coefficients
 if nargout > 1
     e = y-x*beta; % Residuals
 end
