### ISSUE TITLE
running NIAK singularity with slurm system

### ISSUE THREAD

**Issue by yasharz** [SIMEXP/niak#386]
Hi,

I am trying to run NIAK singularity on computecanada which now mainly uses Slurm. I was wondering what are the necessary changes to the instruction here (http://niak.simexp-lab.org/niak_HPC_installation.html) for Slurm system.
Thanks in advance.

**Comment by ltetrel** [comment]
Hi @yasharz,

Not sure to understand exactly your issue but here are an example of a niak script 
[preprocessing_aibl_example.txt](https://github.com/SIMEXP/niak/files/2937793/preprocessing_aibl_example.txt) and the job submission script on a slurm system (like computecanada) 
[preprocessing_job_example.txt](https://github.com/SIMEXP/niak/files/2937798/preprocessing_job_example.txt)

**Comment by yasharz** [comment]
You have answered my question! Thanks a lot.

**Comment by pbellec** [comment]
recently we have started using slurm to request an execution node, and then run niak interactively on that node. There is still parallel processing happening, but only on that node. We need to find a good slurm configuration for distributed compute nodes, but have no such guidelines at the moment.
