### ISSUE TITLE
https online version of the doc is not working

### ISSUE THREAD

**Issue by bpinsard** [SIMEXP/niak#395]
The website for niak and psom with https (referenced by default on google) are not working.
The cause seems to be that it depends on javascript loaded from unencrypted location.

**Comment by pbellec** [comment]
mmmmhhhhh ok :/

I see, so all these lines should load from https?
https://github.com/SIMEXP/niak/blob/gh-pages/index.html#L13-L19

I'll have a look.

**Comment by pbellec** [comment]
ok so I have updated to https, but it does not fix the problem.
flatdoc seems to default to http, and still gets blocked.

It also looks like the project is not maintained anymore https://github.com/rstacruz/flatdoc/issues/100

May be simpler to rebuild with sphinx. 
I'll look into this, I want to learn how to use it anyway.

**Comment by pbellec** [comment]
I have started importing old markdown content in a new repo: 
https://github.com/SIMEXP/niak_docs

It's missing some important material, but that's the core of what is still relevant.

**Comment by pbellec** [comment]
Alright, so the sphinx doc was relatively easy to build, and it does work with https
https://simexp.github.io/niak_docs/build/html/OVERVIEW.html

A few things to tweak, and it will be ready to push on readthedocs

I'll redirect niak.simexp-lab.org there once it's done.

**Comment by pbellec** [comment]
I've finished the port to sphynx. https//niak.simexp-lab.org should now work fine.

Also in the end I decided to leave the website on the gh-pages branch of niak, I would need to reconfigure the DNS, and it's painful.
