### ISSUE TITLE
Test Dataset and Test for scores

### ISSUE THREAD

**Issue by surchs** [SIMEXP/niak#43]
I need a short test dataset and template output for testing of new edits and for later integration into the travis framework. Could be a first testrun for the new github file repo.

**Comment by pbellec** [comment]
So for the  test data, I recommend using the results of the preprocessing, that comes with the target 'target_test_niak_mnc1'. You can model the test after niak_test_region_growing_demoniak, and check how it's added to the integration test suite in niak_test_all lines 158-176.

**Comment by surchs** [comment]
I think it would make sense to add a down-sampled version of the cambridge template to the niak demo dataset.

**Comment by surchs** [comment]
Actually this cannot be closed before we don't update the demoniak_target. Otherwise, the test suite will fail.

**Comment by pbellec** [comment]
@surchs we need to make sure the tests run well first. I have been able to generate the target locally, but I have fails when trying to replicate. You can try on your end. When the test suite runs and we are satistified with the outputs, I'll push the new target to nitrc. Or maybe we will be able to switch to github LFS already.

**Comment by surchs** [comment]
niak now [points to the new target](https://github.com/SIMEXP/niak/commit/0429ee7e7cf01b156ec27f36606dcbd33996fb12) that includes scores.
