### ISSUE TITLE
have a nicer forum

### ISSUE THREAD

**Issue by surchs** [SIMEXP/niak#51]
[This](http://www.discourse.org/) seems like a pretty good candidate.

**Comment by pbellec** [comment]
With the 85% educational rebate, discourse does absolutely seem to be the way to go.

**Comment by poquirion** [comment]
We stick with slack...

**Comment by surchs** [comment]
This was more meant as a replacement for [this conversation graveyard](https://www.nitrc.org/forum/forum.php?forum_id=1821). But I guess we have ignored it for long enough to be closed anyway
