### ISSUE TITLE
Change docker documentation for network access

### ISSUE THREAD

**Issue by surchs** [SIMEXP/niak#62]
Our current [install documentation](http://niak.simexp-lab.org/niak_installation.html) uses a docker call that allows octave in gui but doesn't provide internet access from inside the docker image for machines behind proxies (I think).

I found a solution to this:
the `--net=host` flag provides internet access to the container even in these configs. However, it conflicts with the custom name setting of the machine with `-h niak_machine`. I suggest we drop the custom name and change the default docker call to this:

```
docker run -i -t --privileged --net=host --rm --name niak -v /etc/group:/etc/group -v /etc/passwd:/etc/passwd -v /etc/shadow:/etc/shadow  -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY -v $HOME:$HOME --user $UID simexp/niak /bin/bash -c "cd $HOME; source /opt/minc-itk4/minc-toolkit-config.sh; octave --force-gui; /bin/bash"
```

The container will then have the same name as the host machine which is a little confusing but still better than no net access. Maybe there is even a solution to that.

**Comment by pbellec** [comment]
Fixed.
