### ISSUE TITLE
archive name and warning in niak-with-dependencies

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/niak#67]
when unzipping niak-with-dependencies.zip from release 0.13.1, it unzips to niak, while the default git zip has the version in the name. Having the version in the folder name is quite useful. I also get many warnings like:
warning:  skipped "../" path component(s) in ../niak/extensions/niak_test/niak_test_gb_vars.m

Hopefully this could be suppressed.

**Comment by poquirion** [comment]
Its been fixed in the second release of 0.13.1
