### ISSUE TITLE
ID format restrictions

### ISSUE THREAD

**Issue by ajwood** [SIMEXP/niak#7]
I'm processing data for a study in which subject IDs can contain dashes and/or underscores, which Niak doesn't like.

Could Niak be made to digest a broader range of ID formats?

**Comment by pbellec** [comment]
@poquirion this sounds like a feature we should include asap, would be very useful to have for the GUI. Not completely clear to me at this stage how the user-specified ID will make their way to further processing stages (all the way up to statistical testing) but I don't think this should be a major problem.

**Comment by poquirion** [comment]
We will definitively have to discuss that.

**Comment by pbellec** [comment]
actually octave does not put much restriction on IDs it was a misunderstanding on my end. Also, we have updated the way the grabber works, so I don't think we need to respect much restrictions anymore. To use special characters in IDs, say '-' you would need simply to use
```
files_in.('subject-1').anat = ...
```
