### ISSUE TITLE
installation instructions for docker

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/niak#70]
There are a  number of minor issues in this installation page:
- first, the instructions refer to the latest simexp/niak image, instead of simexp/niak-boss:0.13.1
- The command lines are too long, they should be broken down with \
- It would be more useful to have one line to add a niak alias in .bashrc with the full docker call, instead of just providing the line.
- We should make more clear how to change the mounted directory. In a virtual machine, mounting the $HOME does not make sense, because the mounted file systems point to /media, and thus become unusable inside docker. 
- We need to switch the installation instructions for windows and mac to a virtualbox image, so that users can have access to the GUI. Neurodebian with wheezy provides a very similar experience to a recent ubuntu, everything runs smoothly and the installation is relatively straightforward. Importantly neurodebian has a great tutorial about setting up the virtualbox. so that is documentation we don't need to worry about.

**Comment by poquirion** [comment]
In progress...

**Comment by pbellec** [comment]
really neat tickboxes!

**Comment by surchs** [comment]
I would add [this link](http://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo) on how to run without sudo. It's a big help to have.

**Comment by pbellec** [comment]
I think we have the instructions in the installation tutorial (see the linux section):
http://niak.simexp-lab.org/niak_installation.html

or did I miss something?

**Comment by surchs** [comment]
Oh, yes. The commands look a little different but they probably do the same thing. I noticed permission issues after Budha tried following the install script but he may not have done this step. I'll ckeck.

**Comment by pbellec** [comment]
Done.
