### ISSUE TITLE
niak tests crash on travis

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/niak#72]
Currently the travis builds are crashing. 
https://travis-ci.org/SIMEXP/niak/builds/78303596

It seems that the octave team has removed the binary packages for octave 3.8 from the ppa. https://launchpad.net/~octave/+archive/ubuntu/stable/+packages

There is only octave 4.0. I suggest the following line of action:
- [ ] email the octave team to see if they have a long-term archive of packages. Ideally we would be able to rebuild a docker image even 5 years after it was released. 
- [ ] Switch to octave 4.0. This means update octave and octave lib-dev in the travis and docker files, as well as point all libraries for toolboxes towards the latest versions (image, statistics etc). Currently the versions were frozen to older releases, compatible with octave 3.8. 
- [ ] Pray the goddess that the tests will pass using the target generated with octave 3.8. If not we'll have to investigate what is causing the changes and if it's serious.

**Comment by poquirion** [comment]
I have found the long term 3.8.1 repo path and made it work in docker and travis.
