### ISSUE TITLE
FLAG_FISHER in niak_brick_rmap.m does not appear to be used

### ISSUE THREAD

**Issue by dgmclare** [SIMEXP/niak#76]
The command for generating the connectivity maps is:

maps(:,:,:,num_s) = maps(:,:,:,num_s) + niak_build_rmap(vol,all_seed(:,:,:,num_s));

This will be true whether or not FLAG_FISHER is set to True or False.

**Comment by pbellec** [comment]
I checked the code, and it does look like a bug. I am adding the Fisher transform. This will cause problem if the user specifies a single voxel as seed, as the Fisher transform is going to be Infinity. Not sure how to best address that. I'll leave it at infinity for now, but when I finally get to plug this into a multi-level GLM pipeline, it will have to handle Infinity gracefully.

**Comment by pbellec** [comment]
Fixed in 8307e52a5ca4028f650a10919b08ddbe5c846713
