### ISSUE TITLE
create a niak demo dataset in nifti format

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/niak#81]
* Find where to host it. It should likely live on github like the new targets. Check with @poquirion 
 * Add the download option as 'data_test_niak_nii' in NIAK_WGET

**Comment by poquirion** [comment]
We could add a nii branch to SIMEXP/niak_target and at tags to the targets

**Comment by pbellec** [comment]
Done for the test data http://www.nitrc.org/frs/shownotes.php?release_id=3273

I don't think it's necessary to run systematic tests under both formats. It's something we can do locally from time to time.
