### ISSUE TITLE
Seed maps in niak_brick_scores_fmri incorrectly computed

### ISSUE THREAD

**Issue by surchs** [SIMEXP/niak#89]
Incorrect call to `niak_build_correlation` in [niak_brick_scores_fmri](https://github.com/SIMEXP/niak/blob/master/extensions/surfstab/niak_brick_scores_fmri.m) leads to faulty seed maps. Error was introduced [here](https://github.com/SIMEXP/niak/commit/092555eb53fce1bf5cfb641c5c472382774c2f4d#diff-5f4123bcf60e2419adfa19d76c68af71R349). Suggested fix is to revert to using `corr`

**Comment by surchs** [comment]
Created (new branch)[https://github.com/SIMEXP/niak/tree/iss89] for this

**Comment by pbellec** [comment]
alright now I remember why we changed `corr` for something else. Check that:
```
x = randn(10,3000);
r = corr(x,x);
sum(r(:)>1)
ans =  887
```
this relates to the fact that the sqrt(a).^2 is not equal to a (numerically). This is causing complex numbers to appear in `niak_fisher`
.

**Comment by pbellec** [comment]
this only happens in octave, not matlab.
