### ISSUE TITLE
niak_slice_timing.m

### ISSUE THREAD

**Issue by dgmclare** [SIMEXP/niak#97]
(1) The default option is listed as 'spline'; but in the code, the default is set as 'sinc'; see line 104

(2) If OPT.INTERPOLATION is set to 'linear', 'spline', or 'cubic'; then the program will use 'linear' interpolation -- see line 146/147. The 'linear' interpolation is hard-coded.

**Comment by pbellec** [comment]
thanks so much for catching this! The specified interpolation should now be taken into account:
https://github.com/SIMEXP/niak/blob/master/commands/SI_processing/niak_slice_timing.m#L146

Also I have updated the default and the doc to state that the default interpolation is 'linear', this way niak remains consistent with its previous (effective) behaviour.

**Comment by pbellec** [comment]
Check defaults here
https://github.com/SIMEXP/niak/blob/master/bricks/fmri_preprocess/niak_brick_slice_timing.m#L256-L259

and here:
https://github.com/SIMEXP/niak/blob/master/commands/SI_processing/niak_slice_timing.m#L102-L105

The documentation has been changed accordingly. I am waiting for the results of the tests to close this issue.

**Comment by pbellec** [comment]
Build is passing, I am closing the issue
https://travis-ci.org/SIMEXP/niak/builds/87513137
