### ISSUE TITLE
new QC visualisation

### ISSUE THREAD

**Issue by amanbadhwar** [SIMEXP/niak#98]
The synced version with the xyz coordinates prelisted, seems to misalign the template to structural image. This is not happening with the simpler (older) version of QC.

**Comment by cdansereau** [comment]
what function are you using?
https://github.com/SIMEXP/niak/blob/master/commands/visualization/niak_qc_fmri_preproc.m

I got a look at it and there is no specific slice specified in this function....

**Comment by yassinebha** [comment]
@cdansereau it is the same function but in the qc_project branch

**Comment by yassinebha** [comment]
bug fixed in this commit b6316b0f4c42c905e8f064b7f23136341cd423eb https://github.com/SIMEXP/niak/commit/b6316b0f4c42c905e8f064b7f23136341cd423eb
